### ISSUE TITLE
Breaks and Hangs when Waking Up

### ISSUE THREAD

**Issue by green4don** [adrianlungu/ScreenSleep#1] opened 2020-04-03 17:40 UTC
All seems well until I invoke it and the screens turn off. With key strokes, it usually wakes right back up; and with the click to the "Turn Monitors Off" it waits for activity to wake back up.

But, when woke up, it just hangs, is unresponsive and needs to be killed.

So, unusable.

Don't see what config info to give, probably some file has everything you need, but running latest Windows 10 version Home 1909 build 18363.720

Also, many other similar utilities wait a second or so to ensure that the keystroke used to sleep doesn't wake everything back up. Seems to be that problem here. I would normally look into the code but right now life does not give me the time.

Looking forward to a working version.

Thanks.

**Comment by adrianlungu** [comment] 2020-06-02 21:20
I was unable to reproduce the hanging part, but waking up immediately part should be fixed now:

https://github.com/adrianlungu/ScreenSleep/releases/tag/v1.0.1

**Closed by adrianlungu** 2020-06-02 21:20 UTC
